INSERT INTO places(id, name) VALUES 
    (1,'Sony PSN'),
    (2,'Posto Timbauva'),
    (3,'Uplanner'),
    (4,'Rede Fukami Postos'),
    (5,'Festval Mercado'),
    (6,'Big Supermercado'),
    (7,'Angeloni Supermercado'),
    (8,'Farmacias Nissei'),
    (9,'Loja Sport America'),
    (10,'Loja Centauro'),
    (11,'TOKSTOK loja de móveis'),
    (12,'Santo Grão Cafeteria'),
    (13,'Barbearia Clube'),
    (14,'Barollo Restaurante'),
    (15,'Madero Restaurante'),
    (16,'Rei dos animais Petshop'),
    (17,'Servopa Serviços'),
    (18,'Lojas Americanas'),
    (19,'Batel Estacionamento'),
    (20,'Max Gás de cozinha'),
    (21,'Youse Seguros'),
    (22,'Panvell Farmacias'),
    (23,'Muffato Super Mercados'),
    (24,'My Mob Shopping curitiba loja de acessorios'),
    (25,'Academia Doctor Spider'),
    (26,'Poco Tapas Restaurante')



insert into place_tags (place_id, tag) values 
    (1,'EBW *SONYPLAYSTATN'),
    (21,'YOUSE'),
    (3,'IUGU*Uplanner'),
    (22,'PAG*PanvelFilial566'),
    (18,'LOJAS AMERICANAS 323'),
    (4,'REDE FUKAMI'),
    (5,'FESTVAL REPUBLICA ARGE'),
    (8,'FARCIA NISSEI'),
    (9,'LOJA SPORT AMERICA'),
    (10,'CENTAURO CE 84'),
    (6,'BIG'),
    (24,'MYMOB CURITIBA SHOPPI'),
    (11,'TOKSTOK'),
    (23,'MUFFATO PORTAO 06'),
    (25,'NAPES ARTIGOS ESPORTIV'),
    (12,'SANTO GRAO'),
    (13,'BARBEARIA CLUBE'),
    (5,'FESTVAL SHOPPING'),
    (26,'MATTOS E REBELLO LTDA'),
    (17,'SERVOPA'),
    (14,'MKT COMERCIO DE ALIMEN'),
    (15,'PAG* MaderoIndustria'),
    (5,'FESTVAL REPUBLICA ARGE'),
    (20,'MAX GAS -CT'),
    (5,'FESTVAL REPUBLICA ARGE'),
    (16,'REI DOS ANIMAIS'),
    (19,'COLETIVO BATEL-ESPACO'),
    (5,'FESTVAL BATEL'),
    (7,'SUPERMERCADOS ANGELONI'),
    (18,'LOJAS AMERICANAS 1264')
